#
###################################
# Site wide configuration
####################################
#
title: Ricardo Olsen
email: 
description: Ricardo Olsen's personal website
url: https://riclolsen.github.io # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Recife
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ricardo Olsen
  avatar: ricardo34.jpg
  job: "SCADA, HMI, IoT, Bass"
  bio: "SCADA/HMI expert."
  email: #username
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: riclolsen
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: ricardo-olsen #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  youtubec: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
